# Generated by Django 4.1.7 on 2023-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='preview',
            field=models.TextField(max_length=500, verbose_name='Короткий текст'),
        ),
    ]
