# Generated by Django 4.1.7 on 2023-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cases_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='preview',
            field=models.CharField(max_length=255, verbose_name='Короткий текст'),
        ),
    ]
